=== telota/corpus-coranicum-xml-raw-files/data/Kommentar/Overlay.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.tei-c.org/ns/1.0" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" vc:minVersion="1.1">
 <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xmllang.xsd"/>
 <xs:element name="overlay">
 <xs:annotation>
 <xs:documentation/>
 </xs:annotation>
 <xs:complexType>
 <xs:sequence maxOccurs="unbounded" minOccurs="0">
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="text"/>
 <xs:element ref="akkordeon" maxOccurs="unbounded" minOccurs="0"/>
 </xs:sequence>
 <xs:attribute name="typ" type="xs:string"/>
 <xs:attribute name="webtauglich" type="xs:boolean" use="required"/>
 <xs:attribute name="title" type="xs:string" use="required"/>
 </xs:complexType>
 </xs:element>
 <xs:element name="akkordeon">
 <xs:annotation>
 <xs:documentation>Fließtext, </xs:documentation>
 </xs:annotation>
 <xs:complexType mixed="false">
 <xs:sequence maxOccurs="unbounded" minOccurs="1">
 <xs:element ref="label"/>
 <xs:element ref="text"/>
 </xs:sequence>
 </xs:complexType>
 </xs:element>
 <xs:element name="text">
 <xs:complexType>
 <xs:sequence maxOccurs="unbounded">
 <xs:element ref="p"/>
 </xs:sequence>
 <xs:attribute name="verfasser" type="xs:NCName" use="required"/>
 <xs:attribute name="versstart" use="optional">
 <xs:simpleType>
 <xs:restriction base="xs:integer">
 <xs:pattern value="\d\d\d"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 <xs:attribute name="versend" use="optional">
 <xs:simpleType>
 <xs:restriction base="xs:integer">
 <xs:pattern value="\d\d\d"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 <xs:attribute name="omitstart">
 <xs:simpleType>
 <xs:restriction base="xs:integer">
 <xs:pattern value="\d\d\d"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 <xs:attribute name="omitend">
 <xs:simpleType>
 <xs:restriction base="xs:integer">
 <xs:pattern value="\d\d\d"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 </xs:complexType>
 </xs:element>
 <xs:element name="table">
 <xs:complexType>
 <xs:sequence>
 <xs:element name="head" type="xs:string"/>
 <xs:element form="qualified" maxOccurs="unbounded" name="row">
 <xs:complexType>
 <xs:sequence>
 <xs:element form="qualified" maxOccurs="unbounded" name="cell">
 <xs:complexType mixed="true">
 <xs:sequence maxOccurs="unbounded" minOccurs="0">
 <xs:element ref="q" maxOccurs="unbounded" minOccurs="0"/>
 <xs:element ref="lang" maxOccurs="unbounded" minOccurs="0"/>
 <xs:element ref="hi" maxOccurs="unbounded" minOccurs="0"/>
 <xs:element ref="ref" maxOccurs="unbounded" minOccurs="0"/>
 <xs:element ref="bibl" maxOccurs="unbounded" minOccurs="0"/>
 <xs:element ref="note" maxOccurs="unbounded" minOccurs="0"/>
 </xs:sequence>
 </xs:complexType>
 </xs:element>
 </xs:sequence>
 </xs:complexType>
 </xs:element>
 </xs:sequence>
 <xs:attribute name="cols" type="xs:integer" use="required"/>
 <xs:attribute name="rend" type="xs:NCName" use="required"/>
 <xs:attribute name="rows" type="xs:integer" use="required"/>
 </xs:complexType>
 </xs:element>
 <xs:element name="list">
 <xs:complexType>
 <xs:sequence maxOccurs="unbounded">
 <xs:element ref="label"/>
 <xs:element ref="item"/>
 </xs:sequence>
 <xs:attribute name="rend" type="xs:NCName" use="required"/>
 <xs:attribute name="type" type="xs:NCName" use="required"/>
 </xs:complexType>
 </xs:element>
 <xs:element name="label" nillable="false">
 <xs:complexType mixed="true">
 <xs:sequence maxOccurs="unbounded" minOccurs="0">
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="lang"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="q"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="hi"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="ref"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="bibl"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="note"/>
 </xs:sequence>
 <xs:attribute name="n" type="xs:integer" use="required"/>
 </xs:complexType>
 </xs:element>
 <xs:element name="item">
 <xs:complexType mixed="true">
 <xs:sequence maxOccurs="unbounded" minOccurs="0">
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="lang"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="q"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="hi"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="ref"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="bibl"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="note"/>
 </xs:sequence>
 <xs:attribute name="n" type="xs:integer" use="required"/>
 </xs:complexType>
 </xs:element>
 <xs:element name="p">
 <xs:annotation>
 <xs:documentation>Hier werden die Fließtexte abgelegt.</xs:documentation>
 </xs:annotation>
 <xs:complexType mixed="true">
 <xs:choice minOccurs="0" maxOccurs="unbounded">
 <xs:element ref="hi"/>
 <xs:element ref="lang"/>
 <xs:element ref="lem"/>
 <xs:element ref="q"/>
 <xs:element ref="ref"/>
 <xs:element ref="table"/>
 <xs:element ref="note"/>
 <xs:element ref="list"/>
 <xs:element ref="bibl"/>
 </xs:choice>
 </xs:complexType>
 </xs:element>
 <xs:element name="hi">
 <xs:annotation>
 <xs:documentation>Zur Hervorhebung durch Kursivsetzung und Fettung.</xs:documentation>
 </xs:annotation>
 <xs:complexType mixed="true">
 <xs:sequence maxOccurs="unbounded" minOccurs="0">
 <xs:element ref="lang" maxOccurs="unbounded" minOccurs="0"/>
 <xs:element ref="q" maxOccurs="unbounded" minOccurs="0"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="hi"/>
 <xs:element maxOccurs="unbounded" minOccurs="0" ref="note"/>
 </xs:sequence>
 <xs:attribute name="rend">
 <xs:simpleType>
 <xs:list itemType="rendering"/>
 </xs:simpleType>
 </xs:attribute>
 </xs:complexType>
 </xs:element>
 <xs:element name="note">
 <xs:complexType mixed="true">
 <xs:choice maxOccurs="unbounded" minOccurs="0">
 <xs:element ref="hi"/>
 <xs:element ref="q"/>
 <xs:element ref="lang"/>
 <xs:element ref="ref"/>
 <xs:element ref="bibl"/>
 </xs:choice>
 <xs:attribute name="place" type="xs:string" use="required"/>
 </xs:complexType>
 </xs:element>
 <xs:element name="lang">
 <xs:annotation>
 <xs:documentation>Zur Auszeichung der verwandten Sprachen und Schriften, wobei der markierte Text entweder in Originalschrift oder in lateinischer Transcription vorliegt.
Ein kleine Einführung hier: http://www.w3.org/International/articles/bcp47/
Zur Verwendung von Sprach- und Schrift-Tags gemäß TEI siehe: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CH.html
Zu den Sprachcodes siehe:
http://www.sil.org/iso639-3/codes.asp
Eine Tabelle der Schriftcodes: http://unicode.org/iso15924/iso15924-codes.html</xs:documentation>
 </xs:annotation>
 <xs:complexType>
 <xs:simpleContent>
 <xs:extension base="xs:string">
 <xs:attribute ref="xml:lang" use="required"/>
 </xs:extension>
 </xs:simpleContent>
 </xs:complexType>
 </xs:element>
 <xs:element name="lem" type="xs:string">
 <xs:annotation>
 <xs:documentation>Enthält stehts einen arabischen Transcriptionstext, wird durch ein entsprechendes Stylesheet anschließend kursiviert oder anderweitig hervorgehoben!</xs:documentation>
 </xs:annotation>
 </xs:element>
 <xs:element name="q">
 <xs:annotation>
 <xs:documentation>Mit diesem Element wird auf die Qurʾān- oder Bibelstellen verwiesen. Deshalb sind "type", "versend" und "versstart" zwingend vorgegeben, während das Attribut "buch" nur bei Verweisen mit dem Attribut 'type="bibel"' benötigt wird.</xs:documentation>
 </xs:annotation>
 <xs:complexType mixed="true">
 <xs:attribute name="type" use="required">
 <xs:simpleType>
 <xs:list itemType="quoting"/>
 </xs:simpleType>
 </xs:attribute>
 <xs:attribute name="buch">
 <xs:annotation>
 <xs:documentation>Die Auswahl der Biblischen Bücher ist auf eine Kürzelliste beschränkt, welche der deutschen Einheitsübersetzung entnommen ist.</xs:documentation>
 </xs:annotation>
 <xs:simpleType>
 <xs:list itemType="bibleref"/>
 </xs:simpleType>
 </xs:attribute>
 <xs:attribute name="versstart" use="required">
 <xs:simpleType>
 <xs:restriction base="xs:NMTOKEN">
 <xs:pattern value="\d\d\d\:\d\d\d"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 <xs:attribute name="versend" use="required">
 <xs:simpleType>
 <xs:restriction base="xs:NMTOKEN">
 <xs:pattern value="\d\d\d\:\d\d\d"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 <xs:attributeGroup ref="omit"/>
 <xs:attribute name="id" type="xs:decimal" use="optional"/>
 </xs:complexType>
 </xs:element>
 <xs:element name="ref">
 <xs:annotation>
 <xs:documentation>Tag zum Markieren von Literaturverweisen, beziehungsweise auf Datenbankeinträge (TuK, lectiones, Glossarium).</xs:documentation>
 </xs:annotation>
 <xs:complexType mixed="true">
 <xs:sequence>
 <xs:element minOccurs="0" maxOccurs="unbounded" ref="bibl"/>
 </xs:sequence>
 <xs:attribute name="target" use="required"/>
 </xs:complexType>
 </xs:element>
 <xs:element name="bibl">
 <xs:complexType mixed="true">
 <xs:sequence maxOccurs="unbounded" minOccurs="0">
 <xs:element ref="hi"/>
 </xs:sequence>
 <xs:attribute name="Zotero_Id_1" type="xs:string"/>
 <xs:attribute name="Titel_1" type="xs:string"/>
 </xs:complexType>
 </xs:element>
 <xs:simpleType name="rendering">
 <xs:annotation>
 <xs:documentation>Zur Hervorhebung von Text stehen Kursivierung, Fettung und Hochstellen zur Auswahl.</xs:documentation>
 </xs:annotation>
 <xs:restriction base="xs:string">
 <xs:enumeration value="italic"/>
 <xs:enumeration value="bold"/>
 <xs:enumeration value="superscript"/>
 <xs:enumeration value="text-indent"/>
 <xs:enumeration value="h1"/>
 <xs:enumeration value="h2"/>
 <xs:enumeration value="h3"/>
 <xs:enumeration value="lemma"/>
 </xs:restriction>
 </xs:simpleType>
 <xs:simpleType name="bibleref">
 <xs:annotation>
 <xs:documentation>Die biblischen Bücher werden nach der deutschen Einheitsübersetzung abgekürzt eingetragen; siehe dazu die Liste "bibelbuecher.txt"</xs:documentation>
 </xs:annotation>
 <xs:restriction base="xs:string">
 <xs:enumeration value="Gen"/>
 <xs:enumeration value="Ex"/>
 <xs:enumeration value="Lev"/>
 <xs:enumeration value="Num"/>
 <xs:enumeration value="Dtn"/>
 <xs:enumeration value="Jos"/>
 <xs:enumeration value="Ri"/>
 <xs:enumeration value="Rut"/>
 <xs:enumeration value="1Sam"/>
 <xs:enumeration value="2Sam"/>
 <xs:enumeration value="1Kön"/>
 <xs:enumeration value="2Kön"/>
 <xs:enumeration value="1Chr"/>
 <xs:enumeration value="2Chr"/>
 <xs:enumeration value="Esra"/>
 <xs:enumeration value="Neh"/>
 <xs:enumeration value="Tob"/>
 <xs:enumeration value="Jdt"/>
 <xs:enumeration value="Est"/>
 <xs:enumeration value="1Makk"/>
 <xs:enumeration value="2Makk"/>
 <xs:enumeration value="Ijob"/>
 <xs:enumeration value="Ps"/>
 <xs:enumeration value="Spr"/>
 <xs:enumeration value="Koh"/>
 <xs:enumeration value="Hld"/>
 <xs:enumeration value="Weish"/>
 <xs:enumeration value="Sir"/>
 <xs:enumeration value="Jes"/>
 <xs:enumeration value="Jer"/>
 <xs:enumeration value="Klgl"/>
 <xs:enumeration value="Bar"/>
 <xs:enumeration value="Ez"/>
 <xs:enumeration value="Dan"/>
 <xs:enumeration value="Hos"/>
 <xs:enumeration value="Joël"/>
 <xs:enumeration value="Am"/>
 <xs:enumeration value="Obd"/>
 <xs:enumeration value="Jona"/>
 <xs:enumeration value="Mi"/>
 <xs:enumeration value="Nah"/>
 <xs:enumeration value="Hab"/>
 <xs:enumeration value="Zef"/>
 <xs:enumeration value="Hag"/>
 <xs:enumeration value="Sach"/>
 <xs:enumeration value="Mal"/>
 <xs:enumeration value="Mt"/>
 <xs:enumeration value="Mk"/>
 <xs:enumeration value="Lk"/>
 <xs:enumeration value="Joh"/>
 <xs:enumeration value="Apg"/>
 <xs:enumeration value="Röm"/>
 <xs:enumeration value="1Kor"/>
 <xs:enumeration value="2Kor"/>
 <xs:enumeration value="Gal"/>
 <xs:enumeration value="Eph"/>
 <xs:enumeration value="Phil"/>
 <xs:enumeration value="Kol"/>
 <xs:enumeration value="1Thess"/>
 <xs:enumeration value="2Thess"/>
 <xs:enumeration value="1Tim"/>
 <xs:enumeration value="2Tim"/>
 <xs:enumeration value="Tit"/>
 <xs:enumeration value="Phlm"/>
 <xs:enumeration value="Hebr"/>
 <xs:enumeration value="Jak"/>
 <xs:enumeration value="1Petr"/>
 <xs:enumeration value="2Petr"/>
 <xs:enumeration value="1Joh"/>
 <xs:enumeration value="2Joh"/>
 <xs:enumeration value="3Joh"/>
 <xs:enumeration value="Jud"/>
 <xs:enumeration value="Offb"/>
 </xs:restriction>
 </xs:simpleType>
 <xs:simpleType name="quoting">
 <xs:annotation>
 <xs:documentation>Die verschiedenen Verweismöglichkeiten sind:
 "koran" für einen allgemeien Verweis auf eine bestimmte Qurʾānstelle
 "bibel" für Verweise auf eine Bibelstelle (hier muß dann zusätzlich zu Kapitel und Vers auch noch das Buch angegeben werden)
 "anmerkung" für einen Verweis auf einen Anmerkungstext zu einer bestimmten Qurʾānstelle
 "kommentar" für einen Verweis auf einen Kommentartext zu einer bestimmten Qurʾānstelle
 "datierung" für einen Verweis auf einen Datierungstext zu einer bestimmten Qurʾānsure (als ganzer)
 "literarkritik" für einen Verweis auf einen Text der Kategorie 'literarkritik' zu einer bestimmten Qur'ansure (als ganzer)
 "aufbauinhalt" für einen Verweis auf einen Text der Kategorie 'aufbauinhalt' zu einer bestimmten Qurʾānsure (als ganzer)
 "ueberblick" für einen Verweis auf einen Text der Kategorie 'ueberblick' zu einer bestimmten Qurʾānsure (als ganzer)
 "handschrift" für die Übergabe einer Handschriften-ID</xs:documentation>
 </xs:annotation>
 <xs:restriction base="xs:NCName">
 <xs:enumeration value="koran"/>
 <xs:enumeration value="bibel"/>
 <xs:enumeration value="anmerkung"/>
 <xs:enumeration value="kommentar"/>
 <xs:enumeration value="datierung"/>
 <xs:enumeration value="literarkritik"/>
 <xs:enumeration value="aufbauinhalt"/>
 <xs:enumeration value="ueberblick"/>
 <xs:enumeration value="handschrift"/>
 </xs:restriction>
 </xs:simpleType>
 <xs:attributeGroup name="omit">
 <xs:attribute name="omitstart">
 <xs:simpleType>
 <xs:restriction base="xs:NMTOKEN">
 <xs:pattern value="\d\d\d\:\d\d\d"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 <xs:attribute name="omitend">
 <xs:simpleType>
 <xs:restriction base="xs:NMTOKEN">
 <xs:pattern value="\d\d\d\:\d\d\d"/>
 </xs:restriction>
 </xs:simpleType>
 </xs:attribute>
 </xs:attributeGroup>
</xs:schema>

=== telota/corpus-coranicum-xml-raw-files/data/Kommentar/FAQ.xml
<?xml version="1.0" encoding="UTF-8"?>
<overlay xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Overlay.xsd" typ="FAQ" webtauglich="true" title="Häufige Fragen">
    <text verfasser="tjj">
        <p/>
        <p>
            <hi rend="h1">Häufige Fragen</hi>
        </p>
        <p>
            <hi rend="h2">Allgemein</hi>
        </p>
        <p/>
        <p>
            <hi rend="h2">Is there an English version of this website?</hi>
        </p>
        <p>There is only a German version at the moment.
        </p>
        <p>
            <hi rend="h3">Was ist das Projekt Corpus Coranicum?</hi>
        </p>
        <p>Zum Projekt Corpus Coranicum und zu seinen einzelnen Modulen finden Sie hier (http://corpuscoranicum.de/) Informationen.</p>
        <p>
            <hi rend="h3">Was bietet diese Onlinepublikation?</hi>
        </p>
        <p>Diese Publikation bietet die Ergebnisse der einzelnen Arbeitsmodule des Projekts Corpus Coranicum. Sie beinhaltet erstens eine Dokumentation des Korantextes in seiner handschriftlichen und mündlichen Überlieferungsgestalt, zweitens eine umfassende Datenbank von jüdischen, christlichen, altarabischen und anderen Texten zu einzelnen Koranstellen aus der Umwelt des Korans (TUK) und drittens einen ausführlichen chronologisch - literaturwissenschaftlichen Kommentar.</p>
        <p>
            <hi rend="h3">Wo kann ich generelle Informationen über die Projektmodule finden?</hi>
        </p>
        <p>Allgemeine Informationen über die einzelnen Projektmodule entnehmen Sie bitte dem Textfeld, das sich beim Anklicken des Buttons „Übersicht – Einleitung – Register“ (rechts oben innerhalb der Registerkarte des jeweiligen Moduls) öffnet. Dort finden Sie Informationen zum Stand der Bearbeitung in Form eines Überblicks, eine allgemeine Einleitung in das jeweilige Modul und ggf. weitere Informationen.</p>
        <p>
            <hi rend="h3">Was ist eine Betaversion?</hi>
        </p>
        <p>Diese komplexe, teilweise dynamisch generierte Webseite befindet sich derzeit noch in einer Testphase. Einzelne technische Probleme sind noch nicht behoben. Fehler können unter Umständen auftreten. Deswegen ist diese Webseite als Betaversion gekennzeichnet.</p>
        <p>
            <hi rend="h3">Welche technischen Voraussetzungen sind nötig, um die Webseite benutzen zu können?</hi>
        </p>
        <p>Es werden ein Web 2.0 –fähiger Browser (etwa Firefox, Safari, Internet Explorer, Opera), Sonderzeichen (nicht-ASCII) und nichtlateinische Schriften benötigt. Je nach persönlichen Browsereinstellungen kann es leider dennoch zu Darstellungsschwierigkeiten kommen.</p>
        <p>Für die korrekte Darstellung der nichtlateinischen Zeichen und Schriften ist es nötig, den Font „Coranica“ zu installieren.</p>
        <p>
            <hi rend="h3">Warum wird der arabische Text nicht richtig angezeigt?</hi>
        </p>
        <p>Für die korrekte Darstellung der nichtlateinischen Zeichen und Schriften ist es nötig, den Font „Coranica” zu installieren.</p>
        <p>
            <hi rend="h3">Warum gibt es zu einem Vers nicht in allen Modulen Daten?</hi>
        </p>
        <p>Die verschiedenen Projektmodule bearbeiten nicht zeitgleich dieselben Suren und Verse. Diese asynchrone Arbeitsweise war für die erste Bearbeitungsphase angesichts der Erfordernisse der verschiedenen Module das praktikabelste Vorgehen. In Zukunft wird eine Synchronisierung der Bearbeitungsschwerpunkte angestrebt.</p>
        <p>
            <hi rend="h3">Gibt es eine Suchfunktion?</hi>
        </p>
        <p>Bis jetzt gibt es noch keine allgemeine Suchfunktion.</p>
        <p>
            <hi rend="h3">Kann ich eine Druckansicht von den Daten erstellen, die ich abgerufen habe?</hi>
        </p>
        <p>Es ist möglich, eine Druckansicht von abgerufenen Daten zu erstellen. Klicken Sie dazu auf den Button „Drucken“ in der Navigation auf der linken Seite der Webseite.
        </p>
        <p>
            <hi rend="h3">Gibt es eine Benachrichtigungsfunktion, falls auf der Seite Änderungen vorgenommen werden?</hi>
        </p>
        <p>Derzeit steht diese Möglichkeit noch nicht zur Verfügung.</p>
        <p>
            <hi rend="h3">Warum ist die Übersetzung, die man  in der Navigation sieht (= Paret), eine andere als die im Kommentar (z. B. Sinai)?</hi>
        </p>
        <p>Im Zuge der Kommentierung des Korantextes wird eine projekteigene Übersetzung angefertigt, die die Ergebnisse der Projektarbeit integriert. Da diese Übersetzung jedoch erst mit der Kommentierung der letzten Suren abgeschlossen sein wird, kann sie vorerst noch nicht für alle Suren im entsprechenden Feld der Navigation angezeigt werden. Um das Auffinden und den Abgleich von Koranstellen dennoch zu ermöglichen, wird übergangsweise die Koranübersetzung von Rudi Paret (1979) zur Verfügung gestellt.</p>
        <p>
            <hi rend="h3">Wer ist verantwortlich für diese Webseite?</hi>
        </p>
        <p>Für die Inhalte dieser Webseite zeigen sich die Mitarbeiter des Projekts Corpus Coranicum verantwortlich. In den einzelnen Modulen werden Verfasser von Anmerkungen, Kommentaren oder Übersetzungen namentlich genannt.   
        </p>
        <p>
            <hi rend="h3">An wen richtet sich diese Webseite?</hi>
        </p>
        <p>Diese Webseite richtet sich an alle an der Koranforschung Interessierten. Laien ebenso wie Wissenschaftler sind eingeladen, die hier präsentierten Ergebnisse des akademischen Forschungsvorhabens Corpus Coranicum zu erkunden.
        </p>
        <p>
            <hi rend="h3">An wen kann ich mich bei Fragen wenden?</hi>
        </p>
        <p>Bei Fragen und Problemen wenden Sie sich bitte an folgende E-Mail-Adresse: corpuscoranicum@bbaw.de.</p>
        <p>Wir werden versuchen, Ihre E-Mail so schnell wie möglich zu beantworten. Allerdings kann es in Abhängigkeit vom E-Mail-Aufkommen zu etwas längeren Bearbeitungszeiten kommen. Wir bitten Sie um Ihr Verständnis.</p>
        <p>
            <hi rend="h3">Wie zitiere ich Informationen von dieser Webseite?</hi>
        </p>
        <p>Herausgeber, Verfasser, Bearbeiter oder Übersetzer sind bei allen Daten jeweils aufgeführt und sollten neben der Angabe der vollständigen Webadresse mit angegeben werden. Da es sich bei der Webseite noch um eine Betaversion handelt, sollte jeweils auch das genaue Datum, an dem eine Information abgerufen wurde, mit angeführt werden.</p>
        <p>Gibt es Anwendungsbeispiele? (Video – Michael , N.N.)</p>
        <p/>
        <p>
            <hi rend="h2">Handschriften</hi>
        </p>
        <p>
            <hi rend="h3">Wie viele Koranhandschriften sind derzeit in der Datenbank erfasst?</hi>
        </p>
        <p>Momentan sind ca. 350 Handschriften erfasst, wovon in etwa 70 auch schon für die Online-Publikation freigeschaltet worden sind. Dabei umfassen diese Einträge teilsweise nur ein einzelnes Blatt, teilsweise aber auch mehrere hundert Blätter (z. B. Kodex Wetzstein: 210 fol., Sayyida Zainab: 1087 fol.).</p>
        <p>
            <hi rend="h3">Wie alt ist die älteste datierte Koranhandschrift, die hier eingesehen werden kann?</hi>
        </p>
        <p>??? (Michael)</p>
        <p>
            <hi rend="h3">Wo werden die hier aufgeführten Koranhandschriften aufbewahrt?</hi>
        </p>
        <p>Die Originalhandschriften befinden sich zum einen in öffentlichen Bibliotheken und Museen und zum anderen in privaten Sammlungen. Hie sind insbesondere Bibliotheken in Berlin, Paris, London, St. Petersburg, Tübingen zu nennen. Wichtige Handschriften sind auch in den Museen in Istanbul, Qatar, Bahrain, Chicago aufbewahrt. Für die Erfassung in der Handschriftendatenbank werden bereits vorhandene Digitalisate eingekauft, bzw.  beauftragt.</p>
        <p>
            <hi rend="h3">Was ist das Ziel der Erfassung von Koranhandschriften?</hi>
        </p>
        <p>Die Handschriften werden in einer Datenbank erfasst, wozu möglichst von jeder Seite eine digitale Abbildung in hoher Qualität gehört, auf deren Basis anschließend eine exakte Transliteration des Textes erstellt und gespeichert wird. Diese ermöglichen anschließend einen Vergleich zwischen einzelnen Handschriften und damit auch eine genaue Dokumentation der Entwicklung der Textgestalt des Korans in den Handschriften.</p>
        <p>
            <hi rend="h2">Lesarten (Michael)</hi>
        </p>
        <p>
            <hi rend="h3">Was ist eine Lesart?</hi>
        </p>
        <p/>
        <p>
            <hi rend="h3">Haben Lesarten mit verschiedenen Dialekten zu tun?</hi>
        </p>
        <p/>
        <p>
            <hi rend="h3">Auf welcher Quelle basieren die Lesarten?</hi>
        </p>
        <p/>
        <p>
            <hi rend="h3">Gibt es zwischen Lesarten und Koranhandschriften Differenzen?</hi>
        </p>
        <p/>
        <p>
            <hi rend="h3">Gibt es einen Lesarten-Kanon?</hi>
        </p>
        <p/>
        <p>
            <hi rend="h3">Was ist das Ziel der Erfassung von Lesarten?</hi>
        </p>
        <p/>
        <p>
            <hi rend="h2">Texte aus der Umwelt des Korans (David)</hi>
        </p>
        <p/>
        <p>
            <hi rend="h3">Was ist ein TUK?</hi>
        </p>
        <p>TUK steht für Text(e) aus der Umwelt des Korans. Es handelt sich um Texte, welche im zeitlichen, räumlichen und kulturellen Umfeld des Korans angesiedelt sind und Bezüge zum Korantext aufweisen. Ausführlichere Informationen entnehmen Sie bitte dem Textfeld, das sich beim Anklicken des Buttons „Übersicht – Einleitung – Register“ (rechts oben innerhalb der Registerkarte des jeweiligen Moduls) öffnet.</p>
        <p>
            <hi rend="h3">Werden originalsprachige Texte übersetzt?</hi>
        </p>
        <p>Ja, alle Originaltexte sind ins Deutsche übersetzt.</p>
        <p>
            <hi rend="h3">Wie kann ich mir TUK anzeigen lassen?</hi>
        </p>
        <p>Im Augenblick gibt es zwei Vorgehensweisen:</p>
