=== telota/corpus-coranicum-xml-raw-files/data/Textstruktur/Textstruktur.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" elementFormDefault="qualified" vc:minVersion="1.0" vc:maxVersion="1.1">
    <xs:element name="Quran">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Sure"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Sure">
        <xs:annotation>
            <xs:documentation source="tjj" xml:lang="de">Die Surengliederung orientiert sich an der ersten Kairiner Druckausgabe von 1924.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Hauptteil"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" form="unqualified">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="3" fixed="true"/>
                        <xs:minInclusive value="001"/>
                        <xs:maxInclusive value="114"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="translator" use="required" type="xs:string"/>
            <xs:attribute name="webtauglich" type="xs:boolean" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Hauptteil">
        <xs:annotation>
            <xs:documentation source="tjj" xml:lang="de">Die Hauptteile dienen einer weiteren Untergliederung der Suren anhand inhaltlicher, literaischer Gesichtspunkte.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Abschnitt" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Abschnitt">
        <xs:annotation>
            <xs:documentation source="tjj" xml:lang="de">Gleich den Hauptteilen dienen auch die Abschnitte einer weiteren inhaltlichen, literarischen Untergliederung der Hauptteile einer Sure.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Gesaetz"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Gesaetz">
        <xs:annotation>
            <xs:documentation source="tjj" xml:lang="de">Für die Einteilung in Gesätze zeichnet insbesodnere A. Neuwirth verantwortlich. Der Begriff "Gesätz" beschreibt eine, oft durch entsprechende Reime gekennzeichnete, Versgruppe, welche als eine poetisch-literaische Einheit - nicht unähnlich einer Strophe - in der Reimprosa verstanden werden müssen.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="Vers"/>
                <!--     <xs:element ref="akzeptiert"/>-->
            </xs:choice>
            <!--      <xs:attribute name="akzeptiert" use="required" type="xs:boolean"/>-->
            <xs:attribute name="n" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Vers">
        <xs:annotation>
            <xs:documentation source="tjj" xml:lang="de">Die Einteilung der Verse orientiert sich an der 1924 erschienenen ersten Kairiner Druckausgabe. Die dort verwandte Zählung (kufisch) wird hier zugrundegelegt. Durch die doppelte Vergabe einer Verszahl bei unterschiedlichen Teilversen und Kola wird für die Ausgabe eine Zusammenziehung zweier Verse nach kufischer Zählung ermöglicht. Oder??? tjj</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Teilvers" maxOccurs="unbounded"/>
            </xs:sequence>
            <!--   <xs:attribute name="akzeptiert" type="xs:boolean"/>-->
            <xs:attribute name="n" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits fixed="true" value="3"/>
                        <xs:minInclusive fixed="true" value="000"/>
                        <xs:maxInclusive fixed="true" value="286"/>
                        <xs:pattern value="\d{3}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="Teilvers">
        <xs:annotation>
            <xs:documentation source="tjj" xml:lang="de">Das Element Teilvers dient der Untergliederung der, insbesondere in den medinensichen Suren vorkommenden, überlangen Verse und ermöglicht die überlappende Strukturierung des Qurʾāntextes sowohl anhand der kufischen Zählung, als auch einer literaturwissenschaftlichen Verszählung (bsp. Vers 12a und 12b).</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Kolon"/>
            </xs:sequence>
            <xs:attribute name="n" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="\d{3}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="reim" use="required" type="xs:string"/>
            <xs:attribute name="reimkommentar" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Kolon">
        <xs:annotation>
            <xs:documentation source="tjj" xml:lang="de">Als Kolon bezeichnet man in der Verslehre die rhythmische Elementareinheit von einem oder mehreren Worten, welche einen gliedernde Taktung bilden.</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:attribute name="Einschub" use="required" type="xs:boolean"/>
            <xs:attribute name="lang" use="required" form="unqualified">
                <xs:simpleType>
                    <xs:restriction base="xs:language">
                        <xs:length value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="n" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <!--<xs:element name="akzeptiert" type="xs:boolean"/>-->
</xs:schema>

=== telota/corpus-coranicum-xml-raw-files/data/Textstruktur/Sure107.xml
<?xml version="1.0" encoding="UTF-8"?>
<Quran xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Textstruktur.xsd">
    <Sure id="107" webtauglich="true" translator="Nicolai Sinai">
        <Hauptteil id="0">
            <Abschnitt id="0">
                <Gesaetz n="0">
                    <Vers n="000">
                        <Teilvers n="000" reim="2n/m">
                            <Kolon lang="ar" Einschub="false" n="0">بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ</Kolon>
                            <Kolon lang="de" Einschub="false" n="0">Im Namen Gottes, des barmherzigen Erbarmers!</Kolon>
                        </Teilvers>
                    </Vers>
                </Gesaetz>
                <Gesaetz n="1">
                    <Vers n="001">
                        <Teilvers n="001" reim="2n/m">
                            <Kolon Einschub="false" lang="ar" n="1">أَرَءَيۡتَ ٱلَّذِی يُكَذِّبُ بِٱلدِّينِ</Kolon>
                            <Kolon Einschub="false" lang="de" n="1">Was meinst du von dem, der das Gericht leugnet?</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="002">
                        <Teilvers n="002" reim="2n/m">
                            <Kolon Einschub="false" lang="ar" n="2">فَذَٰلِكَ ٱلَّذِی يَدُعُّ ٱلۡيَتِيمَ</Kolon>
                            <Kolon Einschub="false" lang="de" n="2">Das ist der, der die Waise wegstößt</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="003">
                        <Teilvers n="003" reim="2n/m">
                            <Kolon Einschub="false" lang="ar" n="3">وَلَا يَحُضُّ عَلَىٰ طَعَامِ ٱلۡمِسۡكِينِ</Kolon>
                            <Kolon Einschub="false" lang="de" n="3">und nicht zur Speisung des Armen anhält.</Kolon>
                        </Teilvers>
                    </Vers>
                </Gesaetz>
                <Gesaetz n="2">
                    <Vers n="004">
                        <Teilvers n="004" reim="2n/m">
                            <Kolon Einschub="false" lang="ar" n="4">فَوَيۡلٌۭ لِّلۡمُصَلِّينَ</Kolon>
                            <Kolon Einschub="false" lang="de" n="4">Wehe den Betenden,</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="005">
                        <Teilvers n="005" reim="2n/m">
                            <Kolon Einschub="false" lang="ar" n="5">ٱلَّذِينَ هُمۡ عَن صَلَاتِهِمۡ سَاهُونَ</Kolon>
                            <Kolon Einschub="false" lang="de" n="5">die nicht auf ihr Gebet achtgeben,</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="006">
                        <Teilvers n="006" reim="2n/m">
                            <Kolon Einschub="false" lang="ar" n="6">ٱلَّذِينَ هُمۡ يُرَآءُونَ</Kolon>
                            <Kolon Einschub="false" lang="de" n="6">die nur gesehen werden wollen</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="007">
                        <Teilvers n="006" reim="2n/m">
                            <Kolon Einschub="false" lang="ar" n="7">وَيَمۡنَعُونَ ٱلۡمَاعُونَ</Kolon>
                            <Kolon Einschub="false" lang="de" n="7">und Hilfeleistung verweigern!</Kolon>
                        </Teilvers>
                    </Vers>
                </Gesaetz>
            </Abschnitt>
        </Hauptteil>
    </Sure>
</Quran>

=== telota/corpus-coranicum-xml-raw-files/data/Textstruktur/Sure094.xml
<?xml version="1.0" encoding="UTF-8"?>
<Quran xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Textstruktur.xsd">
    <Sure id="094" webtauglich="true" translator="Nicolai Sinai">
        <Hauptteil id="0">
            <Abschnitt id="0">
                <Gesaetz n="0">
                    <Vers n="000">
                        <Teilvers n="000" reim="2n/m">
                            <Kolon lang="ar" Einschub="false" n="0">بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ</Kolon>
                            <Kolon lang="de" Einschub="false" n="0">Im Namen Gottes, des barmherzigen Erbarmers!</Kolon>
                        </Teilvers>
                    </Vers>
                </Gesaetz>
                <Gesaetz n="1">
                    <Vers n="001">
                        <Teilvers n="001" reim="3Krak">
                            <Kolon Einschub="false" lang="ar" n="1">أَلَمۡ نَشۡرَحۡ لَكَ صَدۡرَكَ</Kolon>
                            <Kolon Einschub="false" lang="de" n="1">Haben wir dir nicht die Brust geweitet,</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="002">
                        <Teilvers n="002" reim="3Krak">
                            <Kolon Einschub="false" lang="ar" n="2">وَوَضَعۡنَا عَنكَ وِزۡرَكَ</Kolon>
                            <Kolon Einschub="false" lang="de" n="2">und haben wir nicht die Bürde von dir genommen,</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="003">
                        <Teilvers n="003" reim="3Krak">
                            <Kolon Einschub="false" lang="ar" n="3">ٱلَّذِیٓ أَنقَضَ ظَهۡرَكَ</Kolon>
                            <Kolon Einschub="false" lang="de" n="3">die deinen Rücken niederdrückte,</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="004">
                        <Teilvers n="004" reim="3Krak">
                            <Kolon Einschub="false" lang="ar" n="4">وَرَفَعۡنَا لَكَ ذِكۡرَكَ</Kolon>
                            <Kolon Einschub="false" lang="de" n="4">und haben wir nicht dein Ansehen erhöht?</Kolon>
                        </Teilvers>
                    </Vers>
                </Gesaetz>
                <Gesaetz n="2">
                    <Vers n="005">
                        <Teilvers n="005" reim="-usrā">
                            <Kolon Einschub="false" lang="ar" n="5">فَإِنَّ مَعَ ٱلۡعُسۡرِ يُسۡرًا</Kolon>
                            <Kolon Einschub="false" lang="de" n="5">Mit dem Schweren kommt Leichtes,</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="006">
                        <Teilvers n="006" reim="-usrā">
                            <Kolon Einschub="false" lang="ar" n="6">إِنَّ مَعَ ٱلۡعُسۡرِ يُسۡرًۭا</Kolon>
                            <Kolon Einschub="false" lang="de" n="6">mit dem Schweren kommt Leichtes!</Kolon>
                        </Teilvers>
                    </Vers>
                </Gesaetz>
                <Gesaetz n="3">
                    <Vers n="007">
                        <Teilvers n="007" reim="3(K)K3b">
                            <Kolon Einschub="false" lang="ar" n="7">فَإِذَا فَرَغۡتَ فَٱنصَبۡ</Kolon>
                            <Kolon Einschub="false" lang="de" n="7">Wenn du nun frei bist, so mühe dich</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="008">
                        <Teilvers n="008" reim="3(K)K3b">
                            <Kolon Einschub="false" lang="ar" n="8">وَإِلَىٰ رَبِّكَ فَٱرۡغَبۡ</Kolon>
                            <Kolon Einschub="false" lang="de" n="8">und strebe deinem Herrn zu!</Kolon>
                        </Teilvers>
                    </Vers>
                </Gesaetz>
            </Abschnitt>
        </Hauptteil>
    </Sure>
</Quran>

=== telota/corpus-coranicum-xml-raw-files/data/Textstruktur/Sure103.xml
<?xml version="1.0" encoding="UTF-8"?>
<Quran xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Textstruktur.xsd">
    <Sure id="103" webtauglich="true" translator="Nicolai Sinai">
        <Hauptteil id="0">
            <Abschnitt id="0">
                <Gesaetz n="0">
                    <Vers n="000">
                        <Teilvers n="000" reim="2n/m">
                            <Kolon lang="ar" Einschub="false" n="0">بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ</Kolon>
                            <Kolon lang="de" Einschub="false" n="0">Im Namen Gottes, des barmherzigen Erbarmers!</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="001">
                        <Teilvers n="001" reim="3Kr">
                            <Kolon Einschub="false" lang="ar" n="1">وَٱلۡعَصۡرِ</Kolon>
                            <Kolon Einschub="false" lang="de" n="1">Beim Spätnachmittag!</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="002">
                        <Teilvers n="002" reim="3Kr">
                            <Kolon Einschub="false" lang="ar" n="2">إِنَّ ٱلۡإِنسَٰنَ لَفِی خُسۡرٍ</Kolon>
                            <Kolon Einschub="false" lang="de" n="2">Der Mensch steckt im Verlust!</Kolon>
                        </Teilvers>
                    </Vers>
                    <Vers n="003">
                        <Teilvers n="003" reim="3Kr">
                            <Kolon Einschub="true" lang="ar" n="3">إِلَّا ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ</Kolon>
                            <Kolon Einschub="true" lang="de" n="3">Außer denen, die glauben und gute Werke tun</Kolon>
                            <Kolon Einschub="true" lang="ar" n="4">وَتَوَاصَوۡا۟ بِٱلۡحَقِّ وَتَوَاصَوۡا۟ بِٱلصَّبۡرِ</Kolon>
                            <Kolon Einschub="true" lang="de" n="4">und einander zur Wahrheit und Geduld anhalten.</Kolon>
                        </Teilvers>
                    </Vers>
                </Gesaetz>
            </Abschnitt>
        </Hauptteil>
    </Sure>
</Quran>
